week-14/quizzes/02-create-react-app.md, week-15/quizzes/01-classes-quiz.md
Mostly just formatting to fit the 80 character line width
=> Formatting

week-14/practices/05-navigation/README.md, week-14/practices/05-navigation/starter/src/index.js
=> Jd navigation edit

week-14/practices/12-react-forms/README.md, week-14/practices/13-react-form-validations/README.md
Just some small things I saw / used "Grammarly" to check as well.
=> typos / grammar in react-forms reading and react-forms-validations-reading

week-15/quizzes/03-reducers.md
Removed note about best practices to match reading.
=> updated explanation to match mod curriculum

week-15/practices/08-thunk-action-creator/thunk-action-creator.md, week-15/practices/08-thunk-action-creator/thunk-action-creator/backend/.env.example, week-15/practices/08-thunk-action-creator/thunk-action-creator/backend/.gitignore, week-15/practices/08-thunk-action-creator/thunk-action-creator/backend/config/database.js, week-15/practices/08-thunk-action-creator/thunk-action-creator/backend/config/index.js, week-15/practices/08-thunk-action-creator/thunk-action-creator/backend/db/migrations/20210805193817-create-article.js, week-15/practices/08-thunk-action-creator/thunk-action-creator/backend/package-lock.json, week-15/practices/08-thunk-action-creator/thunk-action-creator/backend/package.json, week-15/practices/08-thunk-action-creator/thunk-action-creator/frontend/src/components/ArticleList/index.js
* Updated `config/database.js` file to use SQLite3 database
* Added `db:setup` script to `backend/package.json` for setting up the database
* Updated instructions in reading to match the new database stuff
One half of Issue #59
=> Update thunk-action-creator practice to use SQLite3

week-14/practices/12-react-forms/README.md
- added option 2 for setup
- updated instructions to reflect code sandbox instead of localhost
- instructed to console.log state variables to see the changes made with the onChange
=> Js w14 practices 12 react forms

week-14/practices/01-react-functional-component-jsx/README.md
- update setup for codesandbox
- add file comments to code snippits
=> update setup for codesandbox, add file comments to code snippits

week-14/practices/01-react-functional-component-jsx/README.md, week-14/practices/02-react-functional-component-props/README.md
- update setup instructions for codesandbox
=> Js w14 practices 02 react functional component props

week-14/practices/01-react-functional-component-jsx/README.md, week-14/practices/02-react-functional-component-props/README.md, week-14/practices/03-react-functional-component-creating-lists/README.md
- update setup instructions for codesandbox
=> Js w14 practices 03 react functional components creating lists

week-14/practices/01-react-functional-component-jsx/README.md, week-14/practices/02-react-functional-component-props/README.md, week-14/practices/03-react-functional-component-creating-lists/README.md, week-14/practices/04-react-router-intro/README.md
- update setup instructions for codesandbox
=> Js w14 practices 04 react router intro

week-14/practices/01-react-functional-component-jsx/README.md, week-14/practices/02-react-functional-component-props/README.md, week-14/practices/03-react-functional-component-creating-lists/README.md, week-14/practices/04-react-router-intro/README.md, week-14/practices/05-react-router-navigation/README.md
- update setup instructions for codesandbox
=> Js w14 practices 05 react router navigation

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md, week-14/practices/11-react-basic-hooks-useEffect-debug-short-practice/README.md, week-14/practices/14-react-context-part1-short-practice/README.md, week-14/practices/14a-react-context-part2-short-practice/README.md, week-14/practices/14b-react-context-part3-short-practice/README.md, week-14/practices/15-react-custom-hook-practice-short-practice/README.md, week-15/practices/01-react-class-component-intro-short-practice/README.md, week-15/practices/02-react-class-component-lifecycle-methods-short-practice/README.md, week-15/practices/03-react-redux-store-short-practice/README.md, week-15/practices/04-react-redux-actions-reducer-short-practice/README.md
=> Js w15 practices 04 react redux actions

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md, week-14/practices/11-react-basic-hooks-useEffect-debug-short-practice/README.md, week-14/practices/14-react-context-part1-short-practice/README.md, week-14/practices/14a-react-context-part2-short-practice/README.md, week-14/practices/14b-react-context-part3-short-practice/README.md, week-14/practices/15-react-custom-hook-practice-short-practice/README.md, week-15/practices/01-react-class-component-intro-short-practice/README.md, week-15/practices/02-react-class-component-lifecycle-methods-short-practice/README.md, week-15/practices/03-react-redux-store-short-practice/README.md
=> Js w15 practices 03 react redux store

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md, week-14/practices/11-react-basic-hooks-useEffect-debug-short-practice/README.md, week-14/practices/14-react-context-part1-short-practice/README.md, week-14/practices/14a-react-context-part2-short-practice/README.md, week-14/practices/14b-react-context-part3-short-practice/README.md, week-14/practices/15-react-custom-hook-practice-short-practice/README.md, week-15/practices/01-react-class-component-intro-short-practice/README.md, week-15/practices/02-react-class-component-lifecycle-methods-short-practice/README.md
=> Js w15 practices 02 react class component lifecycle

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md, week-14/practices/11-react-basic-hooks-useEffect-debug-short-practice/README.md, week-14/practices/14-react-context-part1-short-practice/README.md, week-14/practices/14a-react-context-part2-short-practice/README.md, week-14/practices/14b-react-context-part3-short-practice/README.md, week-14/practices/15-react-custom-hook-practice-short-practice/README.md, week-15/practices/01-react-class-component-intro-short-practice/README.md
=> Js w15 practices 01 react class components

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md, week-14/practices/11-react-basic-hooks-useEffect-debug-short-practice/README.md, week-14/practices/14-react-context-part1-short-practice/README.md, week-14/practices/14a-react-context-part2-short-practice/README.md, week-14/practices/14b-react-context-part3-short-practice/README.md, week-14/practices/15-react-custom-hook-practice-short-practice/README.md
=> Js w14 practices 15 react custom hook practice

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md, week-14/practices/11-react-basic-hooks-useEffect-debug-short-practice/README.md, week-14/practices/14-react-context-part1-short-practice/README.md, week-14/practices/14a-react-context-part2-short-practice/README.md, week-14/practices/14b-react-context-part3-short-practice/README.md
=> Js w14 practices 14b react context pt3

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md, week-14/practices/11-react-basic-hooks-useEffect-debug-short-practice/README.md, week-14/practices/14-react-context-part1-short-practice/README.md, week-14/practices/14a-react-context-part2-short-practice/README.md
=> Js w14 practices 14a react context pt2

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md, week-14/practices/11-react-basic-hooks-useEffect-debug-short-practice/README.md, week-14/practices/14-react-context-part1-short-practice/README.md
=> Js w14 practices 14 react context pt1

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md
=> Js w14 practices 10 react basic hooks useeffect

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md
=> Js w14 practices 08 react basic hooks usestate

week-14/practices/06-react-router-nesting-short-practice/README.md
=> Js w14 practices 06 react router nesting

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md, week-14/practices/10a-react-basic-hooks-useEffect-api-short-practice/README.md
=> Js w14 practices 10a react basic hooks useffect api

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md, week-14/practices/11-react-basic-hooks-useEffect-debug-short-practice/README.md, week-14/practices/14-react-context-part1-short-practice/README.md, week-14/practices/14a-react-context-part2-short-practice/README.md, week-14/practices/14b-react-context-part3-short-practice/README.md, week-14/practices/15-react-custom-hook-practice-short-practice/README.md, week-15/practices/01-react-class-component-intro-short-practice/README.md, week-15/practices/02-react-class-component-lifecycle-methods-short-practice/README.md, week-15/practices/03-react-redux-store-short-practice/README.md, week-15/practices/04-react-redux-actions-reducer-short-practice/README.md, week-15/practices/05-react-redux-useSelector-useDispatch-short-practice/README.md, week-15/practices/06-react-redux-singleArticle-short-practice/README.md
=> Js w15 practices 06 react redux single article

week-14/practices/06-react-router-nesting-short-practice/README.md, week-14/practices/08-react-basic-hooks-usestate-hook-short-practice/README.md, week-14/practices/10-react-basic-hooks-useEffect-practice-short-practice/README.md, week-14/practices/11-react-basic-hooks-useEffect-debug-short-practice/README.md, week-14/practices/14-react-context-part1-short-practice/README.md, week-14/practices/14a-react-context-part2-short-practice/README.md, week-14/practices/14b-react-context-part3-short-practice/README.md, week-14/practices/15-react-custom-hook-practice-short-practice/README.md, week-15/practices/01-react-class-component-intro-short-practice/README.md, week-15/practices/02-react-class-component-lifecycle-methods-short-practice/README.md, week-15/practices/03-react-redux-store-short-practice/README.md, week-15/practices/04-react-redux-actions-reducer-short-practice/README.md, week-15/practices/05-react-redux-useSelector-useDispatch-short-practice/README.md, week-15/practices/06-react-redux-singleArticle-short-practice/README.md, week-15/practices/07-react-redux-create-input-short-practice/README.md
=> Js w15 practices 07 react redux create input
